@extends('front.includes.container')
@section('content')
<div id="dummyheader"></div>
	<section class="banner-section">
	<div class="banner-inner">
		<div class="homeslider">
			<img src="{{URL::asset('assets/front/images/homeslider/0slider1.jpg')}}" class="img-responsive" alt="slider1">
			<div class="pagetitle-wraper">
				<div class="container">
					<div class="pagetitle">Terms & Conditions</div>
				</div>
			</div>
		</div>	
	</div>	
	<div class="banner-breadcrumb">
  		<div class="container">
  			<div class="row">
  				<div class="col-md-12">
  					<ul class="breadcrumb">
					  <li><a href="{{route('front.index')}}">Home</a></li>					  
					  <li><a href="#">Terms & Conditions</a></li>
				    </ul>
  				</div>
  			</div>
  		</div>
  	</div>
	</section>
    <section class="common-section">
        <div class="container">
            <div class="col-md-12 col-sm-12 col-xs-12 common-content privacy-content">
            <div class="form-group">
                <p><b>About Us</b></p>
                <p>Silkastic is the company from Kanchipuram, India was established in the year 2021 and exclusively designed for selling variety of saree’s to customer choice. Our products can also be shopped all over the world through thru our website <a href="{{route('front.index')}}">www.thesilkastic.com</a>.</p>
                <p><b>General Conditions</b></p>
                <p>This page states the Terms and Conditions under which you (Visitor) may visit this Website. Please read this page carefully. By accessing or using any part of this Website you agree that you have read, understood and agree to be bound by the Terms and Conditions stated here in its entirety.</p>
                <p>These Terms and Conditions supplement (and is in addition to) the terms of our Privacy Policy. Please note that when you agree to be bound by these Terms and Conditions in its entirety, you shall be deemed also to have read, understood and agreed to our Privacy Policy in its entirety.thesilkastic.com, any of its business divisions and / or its subsidiaries, associate companies or subsidiaries to subsidiaries or such other investment companies (in India or abroad) reserve their respective rights to revise these Terms and Conditions at any time by updating this posting. You should visit this page periodically to re-appraise yourself of the Terms and Conditions, because they are binding on all users of this Web Site.</p>
                <p><b>Use of Content</b></p>
                <p>This website allows you to buy saree and other products online. However, all logos, brands and marks appearing in this website, except as otherwise noted, are properties either owned, or used under license, by SILKASTIC and/or its associate entities who feature on this website. The use of these properties or any other content on this site, except as provided in these Terms and Conditions or in the Website content, is strictly prohibited. No trademark or service does not confer or be considered as conferring upon anyone any license under either SILKASTIC or any third party's intellectual property rights.</p>
                <p>You may not sell or modify the content of this Web Site or reproduce, display, publicly perform, distribute, or otherwise use the materials in any way for any public or commercial purpose without the respective organization's or entity's written permission.</p>
                <p><b>Acceptable Site Use</b></p>
                <p><b>Security/General Rules</b></p>
                <p>Visitors are prohibited from violating or attempting to violate the security of the Web site, including, without limitation,<br> (1) accessing data not intended for such user or logging into a server or account which the user is not authorized to access,<br> (2) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization,<br> (3) attempting to interfere with service to any user, host or network, including, without limitation, via means of submitting a virus or "Trojan horse" to the Web site, overloading, "flooding", "mail bombing" or "crashing",<br> (4) sending unsolicited electronic mail, including promotions and/or advertising of products or services. Violations of system or network security may result in civil or criminal liability. SILKASTIC and / or its associate entities will have the right to investigate occurrences that they suspect as involving such violations and will have the right to involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations.</p>
                <p><b>Payment Policy</b></p>
                <p>SILKASTIC and / or its associate entities have the sole discretion to provide the payment term. The payment must be first received by SILKASTIC and / or its associate entities prior to its acceptance of an order. There is no credit given or agreed upon.</p>
                <p>The payment shall be made by Credit / Debit Cards or Net banking or UPI or other payment modes like G-Pay, Paytm, etc. only. At present, Cash on Delivery (COD) option is not available for any products purchase in SILKASTIC website.</p>
                <p>SILKASTIC and / or its associate entities have all the discretion to cancel or deny orders arising due to any errors. Any errors during payment should be sorted by the customer with the payment gateway service provider. SILKASTIC and / or its associate entities are not responsible for any failed transactions by the payment gateway service provider.</p>
                <p><b>Modification of Terms & Conditions of Service</b></p>
                <p>SILKASTIC and / or its associate entities may at any time modify the Terms & Conditions of Use of the Website without any prior notification to you. You can access the latest version of these Terms & Conditions at any given time on the Site. You should regularly review the Terms & Conditions on the Site. In the event the modified Terms & Conditions is not acceptable to you, you should discontinue using the Service. However, if you continue to use the Service you shall be deemed to have agreed to accept and abide by the modified Terms & Conditions of Use of this Site.</p>
                <p><b>Acknowledgement of Rights</b></p>
                <p>Users hereby acknowledge that all rights, titles and interests, including but not limited to rights covered by the intellectual property rights, in and to the site, and that you will not acquire any right, title, or interest in or to the program except as expressly set forth in this agreement. Users will not modify, adapt, translate, prepare derivative works from, decompile, reverse engineer, disassemble or otherwise attempt to derive source code from any of our services, software or documentation, or create or attempt to create a substitute or similar service or product through use of, or access to the program or proprietary information related thereto.</p>
                <p><b>Copyright & Trademark</b></p>
                <p>SILKASTIC and / or its associate entities, its suppliers and licensors expressly reserve all intellectual property rights in all text, programs, products, processes, technology, content and other materials, which appear on this Site. Access to this Website does not confer and shall not be considered as conferring upon anyone any license under any of SAKRO and / or its associate entities or any third party's intellectual property rights. All rights, including copyright, in this website are owned by or licensed to SILKASTIC and / or its associate entities. Any use of this website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the permission of SILKASTIC and / or its associate entities. You may not modify, distribute or re-post anything on this website for any purpose.</p>
                <p>The SILKASTIC /<a href="{{route('front.index')}}" target="_newtab">www.thesilkastic.com</a>  and logos and all related product and service names, design marks and slogans are the trademarks or service marks owned / used by SILKASTIC and / or its associate entities, its affiliates, its partners and its assigns in India. The use or misuse of these trademarks is strictly prohibited. All the rights of selling are reserved with the Company. All other brands, company names, product names, trademarks and service marks are the property of their respective owners. No trademark or service mark license is granted in connection with the materials contained on this Site. Access to this Site does not authorize anyone to use any name, logo or mark in any manner.</p>
                <p>References on this Site to any names, marks, products or services of third parties or hypertext links to third party sites or information are provided solely as a convenience to you and do not in any way constitute or imply SILKASTIC and / or its associate entities endorsement, sponsorship or recommendation of the third party, information, product or service.</p>
                <p>SILKASTIC and / or its associate entities are not responsible for the content of any third party sites and does not make any representations regarding the content or accuracy of material on such sites. If you decide to link to any such third party websites, you do so entirely at your own risk.</p>
                <p>All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this Website (collectively, the "Contents") are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the Website for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents, the Website or any related software. All software used on this Website is the property of SILKASTIC or its licensees and suppliers and protected by Indian and international copyright laws. The Contents and software on this Website may be used only as a shopping resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the Contents on this Website is strictly prohibited. Unless otherwise noted, all Contents are copyrights, trademarks, trade dress and/or other intellectual property owned, controlled or licensed by SILKASTIC, one of its affiliates or by third parties who have licensed their materials to SILKASTIC and are protected by Indian and international copyright laws. The compilation (meaning the collection, arrangement, and assembly) of all Contents on this Website is the exclusive property of SILKASTIC and is also protected by Indian and international copyright laws.</p>
                <p><b>Indemnity</b></p>
                <p>The User unilaterally agree to indemnify and hold harmless, without objection, the Company, its officers, directors, employees and agents from and against any claims, actions and/or demands and/or liabilities and/or losses and/or damages whatsoever arising from or resulting from their use of <a href="{{route('front.index')}}">www.thesilkastic.com</a> or their breach of the terms.</p>
                <p><b>Liability</b></p>
                <p>While all reasonable care has been taken in providing the content on this Web Site, SILKASTIC and / or its associate entities shall not be responsible or liable as to the completeness or correctness of such information and any or all consequential liabilities arising out of use of any information or contents on this Web Site.</p>
                <p>No warranty is given that the Web Site will operate error-free or that this Web Site and its server are free of computer viruses or other harmful mechanisms. If your use of the Web site results in the need for servicing or replacing equipment or data, SILKASTIC and / or its associate entities are not responsible for those costs.</p>
                <p>This Website is provided on an 'as is' basis without any warranties either express or implied whatsoever. SILKASTIC and / or its associate entities to the fullest extent permitted by law, disclaims all warranties, including non-infringement of third parties rights, and the warranty of fitness for a particular purpose and makes no warranties about the accuracy, reliability, completeness, or timeliness of the content, services, software, text, graphics, and links.</p>
                <p><b>Disclaimer of Consequential Damages</b></p>
                <p>In no event shall SILKASTIC and / or its associate entities, or any parties, organizations or entities associated with the corporate brand name thesilkastic.com or otherwise, mentioned at this Web Site be liable for any damages whatsoever (including, without limitations, incidental and consequential damages, lost profits, or damage to computer hardware or loss of data information or business interruption) resulting from the use or inability to use the Web Site and the Web site material, whether based on warranty, contract, tort, or any other legal theory, and whether or not, such organizations or entities were advised of the possibility of such damages</p>
                <p><b>Fraudulent Activities</b></p>
                <p>Fraudulent activities are highly monitored in our site, and if fraud is detected, we shall resort to remedies available to us, and user shall be responsible for all costs and legal fees arising from these fraudulent activities.</p>
                <p><b>Confidentiality</b></p>
                <p>User agree not to disclose information you obtain from us and / or from our clients, advertisers and suppliers. All information submitted to or by an end-user/customer pursuant to a Program is proprietary information of SAKRO and / or its associate entities. Such customer information is confidential and may not be disclosed. Publisher agrees not to reproduce, disseminate, sell, distribute or commercially exploit any such proprietary information in any manner.</p>
                <p><b>Governing Law and Jurisdiction</b></p>
                <p>This Agreement shall be governed by and construed in accordance with the substantive laws of Tamil Nadu, without any reference to conflict-of-laws principles. Any dispute, controversy or difference, which may arise between the parties out of, in relation to or in connection with this Agreement, is hereby irrevocably submitted to the exclusive jurisdiction of the courts, to the exclusion of any other courts without giving effect to its conflict of law provisions, or your actual state or country of residence.</p>
                <p>The entire agreement between the parties with respect to the subject matter hereof is embodied on this agreement and no other agreement relative hereto shall bind either party herein.
Your rights of whatever nature cannot be assigned nor transferred to anybody, and any such attempt may result in termination of this Agreement, without liability to us. However, we may assign this Agreement to any person at any time without notice.
In the event that any provision of these Terms and Conditions is found invalid or unenforceable pursuant to any judicial decree or decision, such provision shall be deemed to apply only to the maximum extent permitted by law, and the remainder of these Terms and Conditions shall remain valid and enforceable according to its terms.
</p>
                <p><b>Termination</b></p>
                <p>This User Agreement is effective unless and until terminated by either you or SILKASTIC. You may terminate this User Agreement at any time, provided that you discontinue any further use of this Site. SILKASTIC may terminate this User Agreement at any time and may do so immediately without notice, and accordingly deny you access to the Site, Such termination will be without any liability to SILKSATIC. Upon any termination of the User Agreement by either you or SILKASTIC, you must promptly destroy all materials downloaded or otherwise obtained from this Site, as well as all copies of such materials, whether made under the User Agreement or otherwise. SILKASTIC's right to any Comments shall survive any termination of this User Agreement. Any such termination of the User Agreement shall not cancel your obligation to pay for the product already ordered from the Website or affect any liability that may have arisen under the User Agreement.</p>
                <p>In case of any queries, we advise you to call us at +91  (Mon – Fri9.30am to 6.30 pm IST) or email your query to the <a href="mailto:thesupport@thesilkastic.com" target="_newtab">support@thesilkastic.com</a>.</p>
            </div>
        </div>
    </div>
</div>
</section>
@endsection